# -*- coding: utf-8 -*-
from __future__ import annotations

EXPORT_DIR = "exports"
DEFAULT_SOLVER_TIME_LIMIT_SECONDS = 10
MIN_SOLVER_TIME_LIMIT_SECONDS = 5
MAX_SOLVER_TIME_LIMIT_SECONDS = 15
DEFAULT_RANDOM_SEED = 0
